### ISSUE TITLE
mlab.mesh error: 'Error displaying widget: model not found'

### ISSUE THREAD

**Issue by TPCollings** [ec-jrc/pyPoseidon#116]
Hello again,

When running through the tutorial scripts I keep getting the error above when trying to view 3D meshes using the mplot function. Example of code and error below. 

Google suggested its a problem with the jupyter lab extension but having exhausted all the potential solutions I'm at a loss. Pyposeidon has been installed with conda and so has all the dependencies. 

Any suggestions of what to try next?

Cheers,

Tom

`mesh.Dataset.mplot.mesh(dim='3D')`
Error displaying widget: model not found

**Comment by brey** [comment]
Hi. First make sure you are running `jlab2` (`itkwidgets` doesn't work yet with `jlab3`). 

Then try:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib jupyterlab-datawidgets itkwidgets ipyevents
```

**Comment by brey** [comment]
Hover over to the upper left corner where a menu appears. Click the icon with the mesh.

**Comment by TPCollings** [comment]
Perfect, thanks George.
