### ISSUE TITLE
Investigate replacing pydap with another library

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#127]
Since pydap 3.3.0 does not get released, we should investigate whether we can remove it as a dependency.

We have a test that uses pydap:
```
pytest -vlx tests/test_meteo.py --runslow -k url
```

The relevant code is:
```
$ ag pydap --python

pyposeidon/meteo.py
315:    # xr_kwargs = kwargs.get("meteo_xr_kwargs", {"engine": "pydap"})
```

**Comment by brey** [comment]
I would open an issue in `xarray` asking how they see the support of `pydap` going forward.

**Comment by brey** [comment]
@pmav99 Is this still an issue? Isn't there a `pypi` release already?

**Comment by pmav99** [comment]
Yes there is a new release. We can close.
