### ISSUE TITLE
Support Geotiff for DEM

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#13]

**Comment by brey** [comment]
@SorooshMani-NOAA, I thought that the support for geo tiff is defined by the xarray engine attribute but apparently you need another function. See http://xarray.pydata.org/en/stable/io.html#rasterio. 

It should be easy to extend pyposeidon to read with rasterio as well.

**Comment by SorooshMani-NOAA** [comment]
Thank you for the update
