### ISSUE TITLE
Consider upgrading cartopy to 0.19

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#14]
We currently use cartopy 0.18. Installing cartopy 0.18 with pip requires that you already have `numpy ` installed in the virtualenv. This is not a huge issue, but it requires that you do:
``` 
pip install numpy
pip install pyposeidon
```
instead of a plain
```
pip install pyposeidon
```

In 0.19 this has been fixed with https://github.com/SciTools/cartopy/pull/1681
Nevertheless, before bumping up the version we should first check if everything works fine with 0.19

@brey since you are more familiar with the visualization functionality, could you check this please? 0.19 is already on conda-forge.

**Comment by brey** [comment]
Looks fine in conda. Already in 0.19 and no problems that I can see. However, we should have some tests for the graphics at some point.
