### ISSUE TITLE
assigning self.obs to a string in shism.py 

### ISSUE THREAD

**Issue by tomsail** [ec-jrc/pyPoseidon#173]
I ran into this while implementing observation on TELEMAC: 

`self.obs` which should be a xr.Dataset is assigned a string [here](https://github.com/ec-jrc/pyPoseidon/blob/9cfd3bbf5598c810004def83b1f43dc5149addd0/pyposeidon/schism.py#L1755C1-L1756C1) 

This leads into the assignation for obs to fail sistematically: 
```
        try:
            stations["location"] = self.obs.location.values
            stations["provider_id"] = self.obs.ioc_code.values
            stations["provider"] = "ioc"
            stations["longitude"] = self.obs.longitude.values
            stations["latitude"] = self.obs.latitude.values
        except:
            pass
```
at [line 1821](https://github.com/ec-jrc/pyPoseidon/blob/9cfd3bbf5598c810004def83b1f43dc5149addd0/pyposeidon/schism.py#L1821C1-L1828C17) 

I would suggest simply to do : 

`self.obs = tg` instead of `self.obs = tg_database`

or even better: to move this assignation a couple lines later and assign it to the normalised dataset [here](https://github.com/ec-jrc/pyPoseidon/blob/9cfd3bbf5598c810004def83b1f43dc5149addd0/pyposeidon/schism.py#L1761)

`self.obs = tg`

**Comment by brey** [comment]
Indeed this is bug. However, it's the other way around. We should replace 

```python
        try:
            stations["location"] = tg.location.values
            stations["provider_id"] = tg.ioc_code.values
            stations["provider"] = "ioc"
            stations["longitude"] = tg.longitude.values
            stations["latitude"] = tg.latitude.values
        except:
            pass
```

This is because the self.obs is saved in the end within the `model.json` file. Saving therein thousands of lines of stations (in the global case) makes the file not readable. Saving only the filename of the `station.json` works much better.
