### ISSUE TITLE
`UnsatisfiableError` when running `conda install -c gbrey pyposeidon`

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [ec-jrc/pyPoseidon#26]
On WSL, after creating a new environment with
```bash
conda create -n pyPoseidon python=3.8
conda activate pyPoseidon
```
and attempting to install from `conda`:
```bash
conda install -c gbrey pyposeidon
```

I get the following output:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
No packages are displayed.

**Comment by zacharyburnettNOAA** [comment]
I ran the following:
```bash
pip install gmsh "--editable=git+https://github.com/pydap/pydap.git@3f6aa190c59e3bbc6c834377a61579b20275ff69#egg=Pydap"
```
and tried installing again, but the `pyposeidon` install failed with the same error.

**Comment by brey** [comment]
Try with the conda-forge channel.

`conda install -c conda-forge pyposeidon`

After install make sure that pydap is **not** installed. Then use the pip command for the pydap.

**Comment by zacharyburnettNOAA** [comment]
> Try with the conda-forge channel.
> `conda install -c conda-forge pyposeidon`
> After install make sure that pydap is **not** installed. Then use the pip command for the pydap.

Thank you! That worked.

```bash
conda install -c conda-forge pyposeidon
pip install gmsh "--editable=git+https://github.com/pydap/pydap.git@3f6aa190c59e3bbc6c834377a61579b20275ff69#egg=Pydap"
```

**Comment by pmav99** [comment]
Yes these warnings are there because we were using stricter version constraints in `pyproject.toml` compared to `environment.yml`. They should be harmless though. In the next release we will try to eliminate them.
