### ISSUE TITLE
Server hosting Natural Earth features seems to be misbehaving

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#33]
The server that hosts the Natural Earth features seems to be misbehaving. I 've noticed both slow responses and plain failures ([example](https://github.com/pmav99/pyPoseidon/runs/3731814377?check_suite_focus=true#step:8:312)).

The files we are trying to download are hosted at: https://naciscdn.org/naturalearth/110m/physical/ne_110m_land.zip
There is an open issue for the server here: https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-913988101
The issue mentions that the data we need can be downloaded from:

- https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_land.zip
- https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_land.zip
- https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_land.zip

The data are a few MBs only. 

There are several options:

1. Do nothing and wait until the server gets restored. 
2. "Inline" them in the project, i.e. `git add` the files in `tests/data`. 
3. host them ourselves on e.g. dropbox

Options 2 and 3 will probably allow us to stop having a hard dependency on `cartopy`, too (it will become an optional dependency just for visualization).

@brey what do you think?

**Comment by pmav99** [comment]
From what I can see, apart from tests, the features are also used as default values inhttps://github.com/ec-jrc/pyPoseidon/blob/06cdcaa21f839f8531e067e9c633cc292fdbe30f/pyposeidon/schism.py#L129-L132

If that is the case, then inlining the features might not be such a bad idea.
On the other hand, if the datasets need to be kept up to date, then probably not.

**Comment by brey** [comment]
As you've spotted this download is triggered by cartopy and geopandas. We could have just an internal set available and defer the user to download and define in the input other optional coastlines. There is already a very simplified global set that will be included for the global grid tests. We can add another one if needed.

**Comment by brey** [comment]
Since we have removed the default coastlines option from the source code there is no point of having this around anymore.
