### ISSUE TITLE
Shapely warnings

### ISSUE THREAD

**Issue by brey** [ec-jrc/pyPoseidon#52]
`ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.`

**Comment by pmav99** [comment]
Also 
```
Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
```
And
```
__getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
```

**Comment by brey** [comment]
I have adjusted our code (see next PL) but geoviews has an issue open for supporting `shapely=1.8 `(holoviz/geoviews/issues/533). 

Until they resolve it, we can pin `shapely` to `1.7.1` to avoid all their warnings.

**Comment by pmav99** [comment]
I think that this can be closed. @brey?

**Comment by brey** [comment]
I thought the same but unpinning shapely brings back the warnings.
