### ISSUE TITLE
Upgrade jigsaw to 0.9.12+

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#57]
We currently pin jigsaw to 0.9.12. This is not currently causing problems, but eventually might cause conda conficts.

The reason we pin the version is that some of the parameters we currently use are causing a segmentation fault in jigsaw 0.9.12+. I tried to update the parameters and the tests are passing but I guess we should check the output in more detail.

https://github.com/dengwirda/jigsaw/issues/47

**Comment by brey** [comment]
Done with #86
