### ISSUE TITLE
`pplot.mesh()` defaults suffer from "over-plotting"

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#75]
`pplot.mesh()` defaults suffer from "over-plotting". For example: 

![image](https://user-images.githubusercontent.com/411196/150113504-7ae41143-ec47-4970-864e-2b03c164afcb.png)

Should we add some default values for `lineweight` and `markersize`?

**Comment by brey** [comment]
In the Tutorial, I always define them as a user. We could define defaults. I will put it in.
