### ISSUE TITLE
Check if we need the binary ffmpeg package as a binary dependency

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/pyPoseidon#76]
ffmpeg is currently used by :
```
$ ag ffmpeg --py
pyposeidon/utils/mplot.py
24:ffmpeg = sys.exec_prefix + "/bin/ffmpeg"
25:os.environ["FFMPEG_BINARY"] = ffmpeg

pyposeidon/utils/pplot.py
26:ffmpeg = sys.exec_prefix + "/bin/ffmpeg"
27:os.environ["FFMPEG_BINARY"] = ffmpeg
```

**Comment by brey** [comment]
This is required for saving the animation to `mp4`. See https://matplotlib.org/stable/api/animation_api.html. 

We could offload that in the future to a utility in the context of using `moviepy`.

**Comment by pmav99** [comment]
Is defining the `FFMPEG_BINARY` env variable necessary? My understanding is that this is a `moviepy` thing.

if it isn't and we just need the `ffmpeg` binary to be available, then how about:

1. Installing `ffmpeg` from conda: https://github.com/ec-jrc/pyPoseidon/blob/08ec86b9f3f0df849fcf2a2c309ee1fb32937cd0/dependencies/binary_deps.yml
2. Removing the `imageio-ffmpeg` python dependency?

**Comment by brey** [comment]
`imageio-ffmpeg` is needed by `moviepy`. `ffmpeg` binary is needed by `Matplotlib` to save `mp4` movies. The first one is not needed until we reuse `moviepy`. The latter is there for having the `Matplotlib` animation saved.

**Comment by brey** [comment]
I think this is settled.

**Comment by pmav99** [comment]
Shouldn't we add the `ffmpeg` binary as a dependency in `viz.yml`? 
https://github.com/ec-jrc/pyPoseidon/blob/c204cc47f394719a0a7ffafe3f69e983acff1968/dependencies/viz.yml

**Comment by brey** [comment]
@pmav99 You are right. I did add it to the `conda` recipe but not on `pyporoject.toml`. Can you do it?
